// Code generated by protoc-gen-go. DO NOT EDIT.
// source: x509svid.proto

package svid

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// X.509 SPIFFE Verifiable Identity Document. It contains the raw X.509
// certificate data as well as a few denormalized fields for convenience.
type X509SVID struct {
	// Certificate and intermediates necessary to form a chain of trust back to a
	// root CA in the bundle (DER encoded).
	CertChain [][]byte `protobuf:"bytes,1,rep,name=cert_chain,json=certChain,proto3" json:"cert_chain,omitempty"`
	// SPIFFE ID in the SVID
	SpiffeId string `protobuf:"bytes,2,opt,name=spiffe_id,json=spiffeId,proto3" json:"spiffe_id,omitempty"`
	// Trust domain of the SVID
	TrustDomain string `protobuf:"bytes,3,opt,name=trust_domain,json=trustDomain,proto3" json:"trust_domain,omitempty"`
	// Expiration timestamp (in seconds since Unix epoch)
	ExpiresAt            int64    `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *X509SVID) Reset()         { *m = X509SVID{} }
func (m *X509SVID) String() string { return proto.CompactTextString(m) }
func (*X509SVID) ProtoMessage()    {}
func (*X509SVID) Descriptor() ([]byte, []int) {
	return fileDescriptor_876f77a3d30643db, []int{0}
}

func (m *X509SVID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_X509SVID.Unmarshal(m, b)
}
func (m *X509SVID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_X509SVID.Marshal(b, m, deterministic)
}
func (m *X509SVID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_X509SVID.Merge(m, src)
}
func (m *X509SVID) XXX_Size() int {
	return xxx_messageInfo_X509SVID.Size(m)
}
func (m *X509SVID) XXX_DiscardUnknown() {
	xxx_messageInfo_X509SVID.DiscardUnknown(m)
}

var xxx_messageInfo_X509SVID proto.InternalMessageInfo

func (m *X509SVID) GetCertChain() [][]byte {
	if m != nil {
		return m.CertChain
	}
	return nil
}

func (m *X509SVID) GetSpiffeId() string {
	if m != nil {
		return m.SpiffeId
	}
	return ""
}

func (m *X509SVID) GetTrustDomain() string {
	if m != nil {
		return m.TrustDomain
	}
	return ""
}

func (m *X509SVID) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

func init() {
	proto.RegisterType((*X509SVID)(nil), "spire.type.svid.X509SVID")
}

func init() { proto.RegisterFile("x509svid.proto", fileDescriptor_876f77a3d30643db) }

var fileDescriptor_876f77a3d30643db = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xab, 0x30, 0x35, 0xb0,
	0x2c, 0x2e, 0xcb, 0x4c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2f, 0x2e, 0xc8, 0x2c,
	0x4a, 0xd5, 0x2b, 0xa9, 0x2c, 0x48, 0xd5, 0x03, 0x09, 0x2b, 0x75, 0x30, 0x72, 0x71, 0x44, 0x98,
	0x1a, 0x58, 0x06, 0x87, 0x79, 0xba, 0x08, 0xc9, 0x72, 0x71, 0x25, 0xa7, 0x16, 0x95, 0xc4, 0x27,
	0x67, 0x24, 0x66, 0xe6, 0x49, 0x30, 0x2a, 0x30, 0x6b, 0xf0, 0x04, 0x71, 0x82, 0x44, 0x9c, 0x41,
	0x02, 0x42, 0xd2, 0x5c, 0x9c, 0xc5, 0x05, 0x99, 0x69, 0x69, 0xa9, 0xf1, 0x99, 0x29, 0x12, 0x4c,
	0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x1c, 0x10, 0x01, 0xcf, 0x14, 0x21, 0x45, 0x2e, 0x9e, 0x92, 0xa2,
	0xd2, 0xe2, 0x92, 0xf8, 0x94, 0xfc, 0x5c, 0x90, 0x6e, 0x66, 0xb0, 0x3c, 0x37, 0x58, 0xcc, 0x05,
	0x2c, 0x04, 0x32, 0x3e, 0xb5, 0x02, 0x64, 0x7f, 0x71, 0x7c, 0x62, 0x89, 0x04, 0x8b, 0x02, 0xa3,
	0x06, 0x73, 0x10, 0x27, 0x54, 0xc4, 0xb1, 0xc4, 0x49, 0x3f, 0x4a, 0x37, 0x3d, 0xb3, 0x24, 0xa3,
	0x34, 0x49, 0x2f, 0x39, 0x3f, 0x57, 0x1f, 0x62, 0xb0, 0x3e, 0xd8, 0xbd, 0xfa, 0x60, 0xc7, 0x43,
	0xd9, 0x20, 0xb7, 0xeb, 0x83, 0xdc, 0x9e, 0xc4, 0x06, 0x16, 0x36, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x47, 0x6e, 0x5b, 0xf8, 0xe5, 0x00, 0x00, 0x00,
}
